site_name: monk docs
operators: &operators
    - monkscript/operators/HTTP.md
    - monkscript/operators/JSON-RPC.md
    - monkscript/operators/JSON.md
    - monkscript/operators/actions.md
    - monkscript/operators/boolean.md
    - monkscript/operators/containers.md
    - monkscript/operators/internals.md
    - monkscript/operators/math.md
    - monkscript/operators/network.md
    - monkscript/operators/numbers.md
    - monkscript/operators/random.md
    - monkscript/operators/strings.md
    - monkscript/operators/types.md
    - monkscript/operators/variables.md
theme:
    name: material
    logo: assets/monk-dolphin-small.svg
    favicon: assets/monk-dolphin-small.svg
    palette:
        scheme: default
        primary: white
        accent: blue
    features:
        - navigation.instant
        - navigation.sections
        - navigation.expand
        - navigation.indexes
extra_css:
    - stylesheets/extra.css
nav:
    - About Monk:
          - "Welcome to Monk": "index.md"
          - "Why Monk?": "use-cases.md"
          - "Monk ecosystem": "key-concepts.md"
          - "Monk vs other software": "comparison.md"
          - Features: "features.md"
          - "Support & Resources": "support.md"
          - Privacy: monk-privacy.md
    - Getting Started:
          - "Getting & Upgrading Monk": "get-monk.md"
          - "Accounts & Authentication": "acc-and-auth.md"
    - Basics:
          - "Monk in 10 minutes": "monk-in-10.md"
          - "Run locally": "guides/running-templates.md"
          - "Inspect workloads": "guides/inspecting-workloads.md"
    - Deploy:
          - Overview: "lifecycle/cluster-overview.md"
          - Create Clusters: "lifecycle/cluster-create-1.md"
          - Operate Clusters: "lifecycle/cluster-operate-1.md"
          - Switch Clusters: "lifecycle/cluster-switch-1.md"
          - Run Templates in a Cluster: "guides/running-templates-cluster.md"
    - Develop Templates:
          - Build a Basic App: "guides/basic-app.md"
          - Define Connections: "guides/connecting-runnables.md"
          - Define Dependencies: "guides/readiness-and-dependency-checks.md"
          - Add Persistent Storage: "guides/02-persistent-storage.md"
          - Add Dynamic Configuration: "guides/04-config-files.md"
          - Add Secrets: "guides/passing-secrets.md"
          - Add Infrastructure: "guides/provisioning-via-templates.md"
          - Add Placement Constraints: "guides/05-affinity.md"
          - Add Load Balancers: "guides/load-balancers.md"
          - Automate with Hooks: "guides/hooks.md"
    - Level Up:
          - Porting Apps from K8s: "guides/k8s-migrate.md"
          - Deploy templates from CI/CD: "guides/ci-cd.md"
          - Multi-Cloud Deployments: "guides/03-multi-cloud.md"
    - Publish to MonkHub:
          - "Publish your templates": "publishers.md"
    - Case Studies:
          - "Chainlink Nodes": "guides/chainlink.md"
    - Troubleshooting:
          - "Template problems": "guides/troubleshooting.md"
    - Reference:
          - MonkScript:
                - "Overview": monkscript/index.md
                - "Working with MonkScript": monkscript/working.md
                - YAML:
                      - Monk YAML: monkscript/yaml/index.md
                      - "Runnables": "monkscript/yaml/runnables.md"
                      - "Groups": "monkscript/yaml/groups.md"
                      - "Services": "monkscript/yaml/services.md"
                - Scripting:
                      - Arrow Scripts: monkscript/scripting-index.md
                      - Cheatsheet: monkscript/scripting-cheatsheet.md
                      - Operators: *operators
          - CLI:
                - "monk": "cli/monk.md"
                - "monkd": "cli/monkd.md"
          - GUI:
                - "Overview": "gui/index.md"
markdown_extensions:
    - admonition
    - abbr
    - def_list
    - pymdownx.details
    - pymdownx.keys
    - pymdownx.inlinehilite
    - pymdownx.highlight
    - pymdownx.tabbed
    - pymdownx.snippets
    - pymdownx.smartsymbols
    - pymdownx.mark
    - pymdownx.superfences:
          custom_fences:
              - name: mermaid
                class: mermaid-experimental
                format: !!python/name:pymdownx.superfences.fence_code_format
    - toc:
          permalink: true
    - pymdownx.emoji:
          emoji_index: !!python/name:materialx.emoji.twemoji
          emoji_generator: !!python/name:materialx.emoji.to_svg

google_analytics:
    - UA-188474701-2
    - auto
